namespace VSOmniBox.UI.Colors
{
    using System;
    using Microsoft.VisualStudio.Shell;

    /// <summary>
    /// Generated with Visual Studio Extension Color Editor, found in:
    /// C:\Program Files (x86)\Microsoft Visual Studio\[version]\[sku]\VSSDK\VisualStudioIntegration\Tools\Bin
    /// </summary>
    internal sealed class VSColors
    {
        #region Autogenerated resource keys
        // These resource keys are generated by Visual Studio Extension Color Editor, and should be replaced when new colors are added to this category.
        public static readonly Guid Category = new Guid("0505f961-c33b-4bde-9f1d-8cb196df1915");

        private static ThemeResourceKey _SearchPopupColorKey;
        private static ThemeResourceKey _SearchPopupBrushKey;
        private static ThemeResourceKey _SearchPopupTextColorKey;
        private static ThemeResourceKey _SearchPopupTextBrushKey;
        public static ThemeResourceKey SearchPopupColorKey { get { return _SearchPopupColorKey ?? (_SearchPopupColorKey = new ThemeResourceKey(Category, "SearchPopup", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchPopupBrushKey { get { return _SearchPopupBrushKey ?? (_SearchPopupBrushKey = new ThemeResourceKey(Category, "SearchPopup", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SearchPopupTextColorKey { get { return _SearchPopupTextColorKey ?? (_SearchPopupTextColorKey = new ThemeResourceKey(Category, "SearchPopup", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SearchPopupTextBrushKey { get { return _SearchPopupTextBrushKey ?? (_SearchPopupTextBrushKey = new ThemeResourceKey(Category, "SearchPopup", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _SearchPopupBorderColorKey;
        private static ThemeResourceKey _SearchPopupBorderBrushKey;
        public static ThemeResourceKey SearchPopupBorderColorKey { get { return _SearchPopupBorderColorKey ?? (_SearchPopupBorderColorKey = new ThemeResourceKey(Category, "SearchPopupBorder", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchPopupBorderBrushKey { get { return _SearchPopupBorderBrushKey ?? (_SearchPopupBorderBrushKey = new ThemeResourceKey(Category, "SearchPopupBorder", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _SearchResultsListColorKey;
        private static ThemeResourceKey _SearchResultsListBrushKey;
        private static ThemeResourceKey _SearchResultsListTextColorKey;
        private static ThemeResourceKey _SearchResultsListTextBrushKey;
        public static ThemeResourceKey SearchResultsListColorKey { get { return _SearchResultsListColorKey ?? (_SearchResultsListColorKey = new ThemeResourceKey(Category, "SearchResultsList", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchResultsListBrushKey { get { return _SearchResultsListBrushKey ?? (_SearchResultsListBrushKey = new ThemeResourceKey(Category, "SearchResultsList", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SearchResultsListTextColorKey { get { return _SearchResultsListTextColorKey ?? (_SearchResultsListTextColorKey = new ThemeResourceKey(Category, "SearchResultsList", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SearchResultsListTextBrushKey { get { return _SearchResultsListTextBrushKey ?? (_SearchResultsListTextBrushKey = new ThemeResourceKey(Category, "SearchResultsList", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _SearchResultsListSelectionColorKey;
        private static ThemeResourceKey _SearchResultsListSelectionBrushKey;
        private static ThemeResourceKey _SearchResultsListSelectionTextColorKey;
        private static ThemeResourceKey _SearchResultsListSelectionTextBrushKey;
        public static ThemeResourceKey SearchResultsListSelectionColorKey { get { return _SearchResultsListSelectionColorKey ?? (_SearchResultsListSelectionColorKey = new ThemeResourceKey(Category, "SearchResultsListSelection", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchResultsListSelectionBrushKey { get { return _SearchResultsListSelectionBrushKey ?? (_SearchResultsListSelectionBrushKey = new ThemeResourceKey(Category, "SearchResultsListSelection", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SearchResultsListSelectionTextColorKey { get { return _SearchResultsListSelectionTextColorKey ?? (_SearchResultsListSelectionTextColorKey = new ThemeResourceKey(Category, "SearchResultsListSelection", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SearchResultsListSelectionTextBrushKey { get { return _SearchResultsListSelectionTextBrushKey ?? (_SearchResultsListSelectionTextBrushKey = new ThemeResourceKey(Category, "SearchResultsListSelection", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _SearchTextBoxColorKey;
        private static ThemeResourceKey _SearchTextBoxBrushKey;
        private static ThemeResourceKey _SearchTextBoxTextColorKey;
        private static ThemeResourceKey _SearchTextBoxTextBrushKey;
        public static ThemeResourceKey SearchTextBoxColorKey { get { return _SearchTextBoxColorKey ?? (_SearchTextBoxColorKey = new ThemeResourceKey(Category, "SearchTextBox", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchTextBoxBrushKey { get { return _SearchTextBoxBrushKey ?? (_SearchTextBoxBrushKey = new ThemeResourceKey(Category, "SearchTextBox", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SearchTextBoxTextColorKey { get { return _SearchTextBoxTextColorKey ?? (_SearchTextBoxTextColorKey = new ThemeResourceKey(Category, "SearchTextBox", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SearchTextBoxTextBrushKey { get { return _SearchTextBoxTextBrushKey ?? (_SearchTextBoxTextBrushKey = new ThemeResourceKey(Category, "SearchTextBox", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _SearchTextBoxBorderColorKey;
        private static ThemeResourceKey _SearchTextBoxBorderBrushKey;
        public static ThemeResourceKey SearchTextBoxBorderColorKey { get { return _SearchTextBoxBorderColorKey ?? (_SearchTextBoxBorderColorKey = new ThemeResourceKey(Category, "SearchTextBoxBorder", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchTextBoxBorderBrushKey { get { return _SearchTextBoxBorderBrushKey ?? (_SearchTextBoxBorderBrushKey = new ThemeResourceKey(Category, "SearchTextBoxBorder", ThemeResourceKeyType.BackgroundBrush)); } }

        private static ThemeResourceKey _SearchToggleButtonColorKey;
        private static ThemeResourceKey _SearchToggleButtonBrushKey;
        private static ThemeResourceKey _SearchToggleButtonTextColorKey;
        private static ThemeResourceKey _SearchToggleButtonTextBrushKey;
        public static ThemeResourceKey SearchToggleButtonColorKey { get { return _SearchToggleButtonColorKey ?? (_SearchToggleButtonColorKey = new ThemeResourceKey(Category, "SearchToggleButton", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchToggleButtonBrushKey { get { return _SearchToggleButtonBrushKey ?? (_SearchToggleButtonBrushKey = new ThemeResourceKey(Category, "SearchToggleButton", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SearchToggleButtonTextColorKey { get { return _SearchToggleButtonTextColorKey ?? (_SearchToggleButtonTextColorKey = new ThemeResourceKey(Category, "SearchToggleButton", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SearchToggleButtonTextBrushKey { get { return _SearchToggleButtonTextBrushKey ?? (_SearchToggleButtonTextBrushKey = new ThemeResourceKey(Category, "SearchToggleButton", ThemeResourceKeyType.ForegroundBrush)); } }

        private static ThemeResourceKey _SearchToggleButtonCheckedColorKey;
        private static ThemeResourceKey _SearchToggleButtonCheckedBrushKey;
        private static ThemeResourceKey _SearchToggleButtonCheckedTextColorKey;
        private static ThemeResourceKey _SearchToggleButtonCheckedTextBrushKey;
        public static ThemeResourceKey SearchToggleButtonCheckedColorKey { get { return _SearchToggleButtonCheckedColorKey ?? (_SearchToggleButtonCheckedColorKey = new ThemeResourceKey(Category, "SearchToggleButtonChecked", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey SearchToggleButtonCheckedBrushKey { get { return _SearchToggleButtonCheckedBrushKey ?? (_SearchToggleButtonCheckedBrushKey = new ThemeResourceKey(Category, "SearchToggleButtonChecked", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey SearchToggleButtonCheckedTextColorKey { get { return _SearchToggleButtonCheckedTextColorKey ?? (_SearchToggleButtonCheckedTextColorKey = new ThemeResourceKey(Category, "SearchToggleButtonChecked", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey SearchToggleButtonCheckedTextBrushKey { get { return _SearchToggleButtonCheckedTextBrushKey ?? (_SearchToggleButtonCheckedTextBrushKey = new ThemeResourceKey(Category, "SearchToggleButtonChecked", ThemeResourceKeyType.ForegroundBrush)); } }
        #endregion
    }
}
