namespace VSOmniBox.UI
{
    using System;
    using Microsoft.VisualStudio.Shell;

    /// <summary>
    /// Generated with Visual Studio Extension Color Editor, found in:
    /// C:\Program Files (x86)\Microsoft Visual Studio\[version]\[sku]\VSSDK\VisualStudioIntegration\Tools\Bin
    /// </summary>
    internal sealed class VSColors
    {
        #region Autogenerated resource keys
        // These resource keys are generated by Visual Studio Extension Color Editor, and should be replaced when new colors are added to this category.
        public static readonly Guid Category = new Guid("0505f961-c33b-4bde-9f1d-8cb196df1915");

        private static ThemeResourceKey _PopupBackgroundColorKey;
        private static ThemeResourceKey _PopupBackgroundBrushKey;
        private static ThemeResourceKey _PopupBackgroundTextColorKey;
        private static ThemeResourceKey _PopupBackgroundTextBrushKey;
        public static ThemeResourceKey PopupBackgroundColorKey { get { return _PopupBackgroundColorKey ?? (_PopupBackgroundColorKey = new ThemeResourceKey(Category, "PopupBackground", ThemeResourceKeyType.BackgroundColor)); } }
        public static ThemeResourceKey PopupBackgroundBrushKey { get { return _PopupBackgroundBrushKey ?? (_PopupBackgroundBrushKey = new ThemeResourceKey(Category, "PopupBackground", ThemeResourceKeyType.BackgroundBrush)); } }
        public static ThemeResourceKey PopupBackgroundTextColorKey { get { return _PopupBackgroundTextColorKey ?? (_PopupBackgroundTextColorKey = new ThemeResourceKey(Category, "PopupBackground", ThemeResourceKeyType.ForegroundColor)); } }
        public static ThemeResourceKey PopupBackgroundTextBrushKey { get { return _PopupBackgroundTextBrushKey ?? (_PopupBackgroundTextBrushKey = new ThemeResourceKey(Category, "PopupBackground", ThemeResourceKeyType.ForegroundBrush)); } }
        #endregion
    }
}
